/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package deepsearch;

import org.junit.Test;

import junit.framework.TestCase;


import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class DeepSearchSearcherTest extends TestCase {

    private DeepSearchSearcher deepSearchSearcher = new DeepSearchSearcher();

    private String jsonString;

    @Override
    protected void setUp() throws Exception {
        Path path = Paths.get(getClass().getClassLoader().getResource("sample.json").toURI());
        jsonString = new String(Files.readAllBytes(path));
    }


    @Test 
    public void testSomeLibraryMethod() {
        DeepSearchSearcher classUnderTest = new DeepSearchSearcher();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testFileLoaded() {
        assertFalse(jsonString.isEmpty());
    }

    @Test
    public void testThatSumWithThisSampleReturns_4 () {
        int actual = deepSearchSearcher.sumOf(jsonString);
        
        assertEquals(4, actual);
    }
}
